-- Create HR user and grant necessary privileges
ALTER SESSION SET "_ORACLE_SCRIPT"=true;

-- Create user
CREATE USER hr IDENTIFIED BY hr123;

-- Grant privileges
GRANT CONNECT, RESOURCE, CREATE SESSION TO hr;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE TO hr;
GRANT UNLIMITED TABLESPACE TO hr;

-- Grant additional privileges for Spring Boot JPA
GRANT CREATE ANY TABLE TO hr;
GRANT ALTER ANY TABLE TO hr;
GRANT DROP ANY TABLE TO hr;
GRANT SELECT ANY TABLE TO hr;
GRANT INSERT ANY TABLE TO hr;
GRANT UPDATE ANY TABLE TO hr;
GRANT DELETE ANY TABLE TO hr;

EXIT;