version: '3.8'

services:
  oracle:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: hr-oracle-db
    environment:
      ORACLE_PWD: oracle123
      ORACLE_CHARACTERSET: AL32UTF8
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./init-scripts:/docker-entrypoint-initdb.d/startup
    networks:
      - hr-network
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sys/oracle123@localhost:1521/XE as sysdba", "@healthcheck.sql"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build: ./backend
    container_name: hr-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle:1521:XE
      SPRING_DATASOURCE_USERNAME: hr
      SPRING_DATASOURCE_PASSWORD: hr123
    ports:
      - "8080:8080"
    depends_on:
      oracle:
        condition: service_healthy
    networks:
      - hr-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: hr-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - hr-network
    restart: unless-stopped

volumes:
  oracle_data:

networks:
  hr-network:
    driver: bridge