version: '3.8'

services:
  oracle:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: hr-oracle-db
    environment:
      ORACLE_PWD: ${ORACLE_ADMIN_PASSWORD}
      ORACLE_CHARACTERSET: AL32UTF8
    ports:
      - "${ORACLE_PORT}:1521"
      - "5500:5500"
    volumes:
      - ${ORACLE_DATA_VOLUME}:/opt/oracle/oradata
      - ./init-scripts:/docker-entrypoint-initdb.d/startup
    networks:
      - ${NETWORK_NAME}
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sys/${ORACLE_ADMIN_PASSWORD}@localhost:1521/${ORACLE_SID} as sysdba", "@healthcheck.sql"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build: ./backend
    container_name: ${BACKEND_HOST}
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@${ORACLE_HOST}:1521:${ORACLE_SID}
      SPRING_DATASOURCE_USERNAME: ${ORACLE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${ORACLE_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    ports:
      - "${BACKEND_PORT}:8080"
    depends_on:
      oracle:
        condition: service_healthy
    networks:
      - ${NETWORK_NAME}
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      args:
        BACKEND_API_URL: ${BACKEND_API_URL}
    container_name: ${FRONTEND_HOST}
    ports:
      - "4200:${FRONTEND_PORT}"
    depends_on:
      - backend
    networks:
      - ${NETWORK_NAME}
    restart: unless-stopped

volumes:
  oracle_data:

networks:
  hr-network:
    driver: bridge