spring:
  application:
    name: hr-application
  
  datasource:
    url: jdbc:oracle:thin:@oracle:1521:XE
    username: hr
    password: hr123
    driver-class-name: oracle.jdbc.OracleDriver
  
  jpa:
    database: oracle
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info